// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxqhnxtzhlrulvvsxqiu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4cWhueHR6aGxydWx2dnN4cWl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4ODU3MzAsImV4cCI6MjA2MDQ2MTczMH0.619Rk-5J8OdUj6SYa_UuOthmlXdCgCfgX3A29e-ePTk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);